name: 'CI'
on: [push, pull_request]
jobs:
  shfmt:
    name: 'Shell format'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2

      - name: 'Test formatting'
        uses: 'bltavares/actions/shfmt@master'
        env:
          SHFMT_ARGS: '-i 2 -ci'
        with:
          path: 'genchroot'

  # shellcheck:
  #   name: 'Shellcheck'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Check out code'
  #       uses: actions/checkout@v2

  #     - name: 'Run Shellcheck'
  #       uses: azohra/shell-linter@develop@v0.2.0
  #       with:
  #         path: 'updateworld'

  semantic_version:
    name: 'Semantic versioning'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.0.4
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.gh_semantic_version }}
